In [91]:
# MOVING AVERAGES USING NORMAL LISTS IN PYTHON

def li_func(li_len):
    li=[]
    for i in range(int(li_len)):
        li.append(int(input()))
    return li
    
def ma_func(li,win):
    inv=len(li)-win+1
    ma_list=[]
    for i in range(inv):
        #print(li[i],li[i+1],li[i+2],":",round(float((li[i]+li[i+1]+li[i+2])/win),2))
        ma_list.append(round(float((li[i]+li[i+1]+li[i+2])/win),2))
    return ma_list

win=int(input("Enter the window value :"))
li_len=int(input("The Length of the list for which you have to determine the MOVING AVERAGES :"))
print("Enter the Values below as prompted : ")
li=li_func(li_len)
print("The MOVING AVERAGE SEQUENCE is as below : ")
print(ma_func(li,win))
#print(ma_func([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3))

Enter the window value :3
The Length of the list for which you have to determine the MOVING AVERAGES :13
Enter the Values below as prompted : 
3
5
7
2
8
10
11
65
72
81
99
100
150
The MOVING AVERAGE SEQUENCE is as below : 
[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]


In [92]:
x = np.array([1, 2, 3, 4, 5])
print("The input array is : [1,2,3,4,5]")
N=int(input("Enter N-value : "))
print("Vander Matrix in INCREASING ORDER : ")
print(np.column_stack([x**(i) for i in range(N)]))
print("Vander Matrix in DECREASING ORDER : ")
print(np.column_stack([x**(N-1-i) for i in range(N)]))

The input array is : [1,2,3,4,5]
Enter N-value : 9
Vander Matrix in INCREASING ORDER : 
[[     1      1      1      1      1      1      1      1      1]
 [     1      2      4      8     16     32     64    128    256]
 [     1      3      9     27     81    243    729   2187   6561]
 [     1      4     16     64    256   1024   4096  16384  65536]
 [     1      5     25    125    625   3125  15625  78125 390625]]
Vander Matrix in DECREASING ORDER : 
[[     1      1      1      1      1      1      1      1      1]
 [   256    128     64     32     16      8      4      2      1]
 [  6561   2187    729    243     81     27      9      3      1]
 [ 65536  16384   4096   1024    256     64     16      4      1]
 [390625  78125  15625   3125    625    125     25      5      1]]


In [94]:
print(np.array([x**(N-1-i) for i in range(N)]))
print("========================================")
print(np.array([x**(i) for i in range(N)]))
#print(np.vstack([x**(i) for i in range(N)]))
#print(np.vstack([x**(N-1-i) for i in range(N)]))

[[     1    256   6561  65536 390625]
 [     1    128   2187  16384  78125]
 [     1     64    729   4096  15625]
 [     1     32    243   1024   3125]
 [     1     16     81    256    625]
 [     1      8     27     64    125]
 [     1      4      9     16     25]
 [     1      2      3      4      5]
 [     1      1      1      1      1]]
[[     1      1      1      1      1]
 [     1      2      3      4      5]
 [     1      4      9     16     25]
 [     1      8     27     64    125]
 [     1     16     81    256    625]
 [     1     32    243   1024   3125]
 [     1     64    729   4096  15625]
 [     1    128   2187  16384  78125]
 [     1    256   6561  65536 390625]]
